import { LoginTemplate } from '@/templates/login';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Include - Login',
  description: 'Generated by create next app',
};

export default function Login() {
  return <LoginTemplate />;
}
