import { AdminTemplate } from '@/templates/admin';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Include - Admin',
  description: 'Generated by create next app',
};

export default function Home() {
  return <AdminTemplate />;
}
