import { HelpCenterTemplate } from '@/templates/helpcenter';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Boilerplate',
  description: 'Generated by create next app',
};

export default function Helpcenter() {
  return <HelpCenterTemplate />;
}
